name: Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Tera Term
        run: choco install -y teraterm
        shell: powershell
      - name: Run syntax check
        shell: bash
        run: ./test_macros.sh
